### ISSUE TITLE
Hi! I need logs!

### ISSUE THREAD

**Issue by AugustoResende** [lvlup-pro/starter#4]
You can make logs for the launcher?

**Comment by SystemZ** [comment]
Hi, what logs do you need?

**Comment by GabrielAugustoTI** [comment]
Game logs!
http://prntscr.com/d6pv8l

**Comment by SystemZ** [comment]
It's possible to implement but unfortunately I don't have time to implement it.

**Comment by GabrielAugustoTI** [comment]
:(

**Comment by GabrielAugustoTI** [comment]
You can implement now?

**Comment by SystemZ** [comment]
Sorry, due to insufficient interest this project may be now considered as discontinued.

I unfortunately can't provide free support for this repo anymore.
If you are interested in paid support, write me at mail from footer of my page http://systemz.pl/ for quote.

You may search for other developer too, code is open source.
